### ISSUE TITLE
یعنی واقعا متاسف ام واسه داکیومنت نویسیتون

### ISSUE THREAD

**Issue by nimaamiri92** [ghasedakapi/ghasedak-php#3]

**Comment by AhYousefi** [comment]
بنده هم اضافه میکنم همین موردرا واقعا تاسف داره

**Comment by sxshateri** [comment]
در این شرکت رو باید تخته کرد با این داکیومنتشون. باید بشینیم کل کد رو بخونیم تا بفهمیم چی به چیه؟

**Comment by mohammadnazarirad** [comment]
> در این شرکت رو باید تخته کرد با این داکیومنتشون. باید بشینیم کل کد رو بخونیم تا بفهمیم چی به چیه؟

بله منم با شما موافق بودم ولی الان به صورت اتفاقی نیاز شد دوباره سر بزنم دیدم خیلی بهتر شده
