### ISSUE TITLE
Not working on version 6.2 of Laravel

### ISSUE THREAD

**Issue by mohamad-sadegh** [ghasedakapi/ghasedak-php#4]
Hello friends,
I have a project that works with this code structure in version 5.7 :
```
$smsWebService = new \Ghasedak\GhasedakApi('MyApiKey');
$smsWebService->Verify("$phone", 1, "freelearningreset", "$code");
```
But that's not working in version 6. 

The error text is: "template is invalid"

Where's the problem?

Thank you!

**Comment by ahoseinpour** [comment]
Hi
Thank you very much for using ghasedak.io

The error text is: "template is invalid"

This template has been rejected , Please use an approved template.

**Comment by mohamad-sadegh** [comment]
Thanks for your response the problem was solved. 👍
