### ISSUE TITLE
مشکل استفاده روی هاست

### ISSUE THREAD

**Issue by Pooria4484** [ghasedakapi/ghasedak-php#5]
چطوری روی هاست سی پنل از پکیجتون استفاده کنیم ، دسترسی به کمپوزر ندارم

**Comment by ahoseinpour** [comment]
سلام برای استفاده ، کامپوزر داخل لوکال نصب کنید و از پکیج پیامک قاصدک استفاده کنید. بعد فایل های مورد نظرتون رو به هاست سی پنل انتقال بدید
